github.com:
    users:
        micheledipace:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: micheledipace
